#docker run --rm -it -v ./src:/code:ro -p 3000:3000 code-lab-nodejs npm start
services:
    app:
        build:
            context: .
        command: npm run build
        ports:
            - "3000:3000"
        volumes:
            - .:/opt/app/
            - /opt/app/node_modules
        environment:
            DB_SCHEMA: postgres
            DB_USER: postgres
            DB_PASSWORD: postgres
            DB_HOST: postgres
        depends_on:
            - postgres
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports: 
            - '5432:5432'
        volumes:
            - db:/var/lib/postgresql/data
volumes:
    db: {}